app:
  employeeRepoFilename: employee.json
  outputFilePath: output.txt

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/management-app
      database: xcc

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb+srv://eddyheinz:${MONGO_PW}@xcc.7wk1k.mongodb.net/management-app?retryWrites=true&w=majority&appName=xcc

---
spring:
  config:
    activate:
      on-profile: integration-test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: integration-test

adapter:
  randomEmployee:
    baseUrl: http://localhost:10400/random-employee
