name: Tag-Based Deployment

on:
  push:
    tags:
      - "*.*.*"

    branches:
      - master
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/xcc-employee-app
          SHA_TAG=${GITHUB_SHA}
          docker build -t ${IMAGE_NAME}:${SHA_TAG} -t ${IMAGE_NAME}:latest .
          
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [ "$BRANCH_NAME" == "master" ] || [ "$BRANCH_NAME" == "develop" ]; then
                docker build -t ${IMAGE_NAME}:${BRANCH_NAME} .
            fi    

      - name: Push Docker Image
        run: |
          docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/xcc-employee-app

  

          
