name: Tag-Based Deployment

on:
  push:
    tags:
      - "*.*.*"

    branches:
      - master
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/xcc-employee-app
          TAG=${GITHUB_REF##*/}
          docker build -t ${IMAGE_NAME}:${TAG} -t ${IMAGE_NAME}:latest .

      - name: Push Docker Image
        run: |
          docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/xcc-employee-app

  

          
